<?php
/* CHISIMBA_GENERIC_FILE_PICKER: server-rendered transport */
if (!$GLOBALS['kewl_entry_point_run']) { die('You cannot view this page directly'); }
$t = function ($key) { return $this->objLanguage->languageText('mod_filemanager_picker_'.$key, 'filemanager'); };
$data = is_array($pickerData) ? $pickerData : array();
$ok = !empty($data['ok']);
$location = $ok && isset($data['location']) ? (string) $data['location'] : '';
$folder = $ok && !empty($data['folder']['id']) ? (string) $data['folder']['id'] : '';
$target = isset($pickerTarget) ? (string) $pickerTarget : '';
$makeUrl = function ($nextLocation, $nextFolder) use ($pickerPolicy, $target) {
    return html_entity_decode($this->uri(array(
        'action' => 'filepicker', 'policy' => $pickerPolicy, 'target' => $target,
        'location' => $nextLocation, 'folder' => $nextFolder
    ), 'filemanager', '', '', false, true), ENT_QUOTES, 'UTF-8');
};
$currentUrl = $makeUrl($location, $folder);
$uploaded = is_array($pickerUploadedFile) ? $pickerUploadedFile : null;
$policyDetails = $ok && !empty($data['policyDetails']) && is_array($data['policyDetails']) ? $data['policyDetails'] : array();
$pickerTitle = $t(isset($policyDetails['titleKey']) ? $policyDetails['titleKey'] : 'select_pdf');
$pickerUpload = $t(isset($policyDetails['uploadKey']) ? $policyDetails['uploadKey'] : 'upload_pdf');
$pickerAccept = isset($policyDetails['accept']) ? (string) $policyDetails['accept'] : 'application/pdf,.pdf';
$pickerIcon = isset($policyDetails['icon']) ? (string) $policyDetails['icon'] : 'pdf';
$folderIcon = '<svg class="picker-icon picker-folder-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6.5h6l2 2h10v9.5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M3 9h18"/></svg>';
$fileIcons = array(
    'image' => '<svg class="picker-icon picker-image-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9" r="1.5"/><path d="m4 17 5-5 4 4 2-2 5 4"/></svg>',
    'audio' => '<svg class="picker-icon picker-audio-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M9 18V5l10-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="16" cy="16" r="3"/></svg>',
    'pdf' => '<svg class="picker-icon picker-pdf-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 2.5h8l4 4V21H6z"/><path d="M14 2.5v4h4"/><path d="M8.5 16.5h7M8.5 13h7M8.5 9.5h2.5"/></svg>',
    'zip' => '<svg class="picker-icon picker-zip-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 2.5h8l4 4V21H6z"/><path d="M14 2.5v4h4"/><path d="M11 3v2h2V3M11 7h2v2h-2M11 11h2v2h-2M10.5 15h3v3h-3z"/></svg>'
);
$fileIcon = isset($fileIcons[$pickerIcon]) ? $fileIcons[$pickerIcon] : $fileIcons['pdf'];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($pickerTitle, ENT_QUOTES, 'UTF-8')?></title>
<style>*{box-sizing:border-box}body{font:16px system-ui,sans-serif;margin:0;padding:1rem;color:#263238}.locations{display:flex;gap:.5rem;margin:1rem 0;flex-wrap:wrap}.locations a[aria-current="true"]{background:#075985;color:#fff}header{display:flex;gap:.75rem;align-items:center;flex-wrap:wrap}h1{font-size:1.3rem;margin:0 auto 0 0}button,input,.button{font:inherit}.button,button{display:inline-block;padding:.55rem .8rem;cursor:pointer;border:1px solid #94a3b8;border-radius:4px;background:#fff;color:#263238;text-decoration:none}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:.75rem}.item{min-height:88px;border:1px solid #cfd8dc;border-radius:10px;background:#fff;padding:.8rem;text-align:left;width:100%}.item{color:#263238;text-decoration:none;transition:background-color .15s ease,border-color .15s ease,color .15s ease}.item-content{display:flex;gap:.7rem;align-items:flex-start}.item-copy{min-width:0}.picker-icon{width:1.55rem;height:1.55rem;flex:0 0 auto;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.picker-folder-icon{color:#b7791f}.picker-pdf-icon{color:#c62828}.picker-image-icon{color:#087f5b}.picker-audio-icon{color:#6d28d9}.picker-zip-icon{color:#b45309}.item strong{display:block;overflow-wrap:anywhere}.meta{font-size:.85rem;color:#546e7a}.item:hover,.item:focus{background:#075985;border-color:#075985;color:#fff;outline:3px solid rgba(14,165,233,.3);outline-offset:1px}.item:hover .meta,.item:focus .meta,.item:hover .picker-icon,.item:focus .picker-icon{color:#fff}.status{min-height:1.5rem;margin:1rem 0}.upload{display:flex;gap:.5rem;align-items:center;flex-wrap:wrap}section{margin-top:1.25rem}.error{color:#b91c1c}</style></head><body>
<header><button id="cancel" type="button"><?=htmlspecialchars($t('cancel'), ENT_QUOTES, 'UTF-8')?></button><?php if ($ok && !empty($data['folder']['parentId'])): ?><a class="button" href="<?=htmlspecialchars($makeUrl($location, $data['folder']['parentId']), ENT_QUOTES, 'UTF-8')?>"><?=htmlspecialchars($t('parent_folder'), ENT_QUOTES, 'UTF-8')?></a><?php endif; ?><h1><?=htmlspecialchars($pickerTitle, ENT_QUOTES, 'UTF-8')?></h1></header>
<?php if ($ok): ?><nav class="locations" aria-label="<?=htmlspecialchars($t('locations'), ENT_QUOTES, 'UTF-8')?>"><?php foreach ((array) $data['locations'] as $item): ?><a class="button" aria-current="<?=$item['key'] === $location ? 'true' : 'false'?>" href="<?=htmlspecialchars($makeUrl($item['key'], ''), ENT_QUOTES, 'UTF-8')?>"><?=htmlspecialchars($item['label'], ENT_QUOTES, 'UTF-8')?></a><?php endforeach; ?></nav><?php endif; ?>
<?php if ($pickerUploadError !== ''): ?><div class="status error" role="alert"><?=htmlspecialchars($pickerUploadError, ENT_QUOTES, 'UTF-8')?></div><?php elseif (!$ok): ?><div class="status error" role="alert"><?=htmlspecialchars(isset($data['error']['message']) ? $data['error']['message'] : '', ENT_QUOTES, 'UTF-8')?></div><?php elseif ($folder !== ''): ?><div class="status"><?=htmlspecialchars($data['folder']['path'], ENT_QUOTES, 'UTF-8')?></div><?php endif; ?>
<?php if ($ok && !empty($data['capabilities']['upload'])): ?><form class="upload" method="post" enctype="multipart/form-data" action="<?=htmlspecialchars($currentUrl, ENT_QUOTES, 'UTF-8')?>"><label for="file"><?=htmlspecialchars($pickerUpload, ENT_QUOTES, 'UTF-8')?></label><input id="file" name="file" type="file" accept="<?=htmlspecialchars($pickerAccept, ENT_QUOTES, 'UTF-8')?>" required><button type="submit"><?=htmlspecialchars($t('upload'), ENT_QUOTES, 'UTF-8')?></button></form><?php endif; ?>
<?php if ($ok): ?><section><div class="grid"><?php foreach ((array) $data['folders'] as $item): ?><a class="button item" href="<?=htmlspecialchars($makeUrl($location, $item['id']), ENT_QUOTES, 'UTF-8')?>"><span class="item-content"><?=$folderIcon?><span class="item-copy"><strong><?=htmlspecialchars($item['name'], ENT_QUOTES, 'UTF-8')?></strong></span></span></a><?php endforeach; ?></div></section>
<section><div class="grid"><?php foreach ((array) $data['files'] as $item): ?><button class="item choose" type="button" data-file="<?=htmlspecialchars(json_encode($item, JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE), ENT_QUOTES, 'UTF-8')?>"><span class="item-content"><?=$fileIcon?><span class="item-copy"><strong><?=htmlspecialchars($item['name'], ENT_QUOTES, 'UTF-8')?></strong><span class="meta"><?=htmlspecialchars($item['mimetype'].' · '.$item['size'].' bytes', ENT_QUOTES, 'UTF-8')?></span></span></span></button><?php endforeach; ?></div><?php if (empty($data['files'])): ?><div class="status"><?=htmlspecialchars($t('no_files'), ENT_QUOTES, 'UTF-8')?></div><?php endif; ?></section><?php endif; ?>
<script>(function(){'use strict';var target=<?=json_encode($target)?>,uploaded=<?=json_encode($uploaded, JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE)?>;function choose(file){if(window.opener&&typeof window.opener.ChisimbaFilePickerReceive==='function'){window.opener.ChisimbaFilePickerReceive(target,file);window.close();}}document.getElementById('cancel').onclick=function(){window.close();};Array.prototype.forEach.call(document.querySelectorAll('.choose'),function(b){b.onclick=function(){choose(JSON.parse(b.getAttribute('data-file')));};});if(uploaded){choose(uploaded);}})();</script></body></html>